/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author USER
 */
public class Ventana extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setSize(550, 450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaAgenda = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiquetaCorreo = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        campoCelular = new javax.swing.JTextField();
        etiquetaCelular = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        mostrarContactos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaAgenda.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAgenda.setText("Agenda de Contactos");
        panel.add(etiquetaAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 480, -1));

        etiquetaNombre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etiquetaNombre.setText("Nombre:");
        panel.add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 80, -1, -1));

        campoNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panel.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 77, 285, -1));

        etiquetaCorreo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etiquetaCorreo.setText("Correo:");
        panel.add(etiquetaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 127, -1, -1));

        campoCorreo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panel.add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 124, 285, -1));

        campoCelular.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        panel.add(campoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 171, 285, -1));

        etiquetaCelular.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etiquetaCelular.setText("Celular:");
        panel.add(etiquetaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 174, -1, -1));

        botonGuardar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonGuardar.setText("Guardar Contacto");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        panel.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 218, -1, -1));

        Menu.setText("Menú");
        Menu.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        mostrarContactos.setText("Mostrar contactos");
        mostrarContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContactosActionPerformed(evt);
            }
        });
        Menu.add(mostrarContactos);
        Menu.add(jSeparator1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Menu.add(Salir);

        barraMenu.add(Menu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Archivo archivo = new Archivo();
        archivo.crearArchivo();
        
        String nombre,correo,celular;
        
        nombre = campoNombre.getText();
        correo = campoCorreo.getText();
        celular = campoCelular.getText();
        
        Persona persona = new Persona(nombre, correo, celular);
        
        archivo.escribirTexto(persona);
        
        campoNombre.setText("");
        campoCorreo.setText("");
        campoCelular.setText("");
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void mostrarContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContactosActionPerformed
        VentanaContactos ventanaC = new VentanaContactos(this, true);
        ventanaC.setVisible(true);
    }//GEN-LAST:event_mostrarContactosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoCelular;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel etiquetaAgenda;
    private javax.swing.JLabel etiquetaCelular;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mostrarContactos;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
